name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "cloud-mail-db"
database_id = "15a26090-b6b2-442a-9010-b94ec72ba01e"

[[kv_namespaces]]
binding = "KV"
id = "54b910e7f77047c08cd7a83424eac824"

[ai]
binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["*/30 * * * *", "0 16 * * *"]

[vars]
domain = ["aichat.center"]
admin = "admin@aichat.center"
jwt_secret = "2R3njZ0KzSdpYscTIHJQMgaqbD6Uv4Am"

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
